# Laptop (MSI): x86_64, NVIDIA RTX 3050 Mobile + Intel iGPU hybrid.
#
# Only the hardware/boot/GPU/printing specifics live here — locale, fonts, the
# user account, Sway baseline, portals, nix.settings, GC, etc. all come from
# hosts/_common/default.nix.

{ config, pkgs, ... }:

{
  imports = [
    ../_common/default.nix
    ./hardware-configuration.nix # generated by `nixos-generate-config`
  ];

  networking.hostName = "nixos";

  # --- Boot ---
  boot.loader.systemd-boot.enable = true;
  # ESP is 1 GB. Each entry ≈ 66 MB (13 MB kernel + 53 MB initrd; NVIDIA is
  # intentionally NOT in the initrd, so it's small). 5 entries ≈ 340 MB,
  # leaving ~680 MB headroom. Stay ≤ ~10.
  boot.loader.systemd-boot.configurationLimit = 5;
  boot.loader.efi.canTouchEfiVariables = true;
  # Boot immediately — no menu shown. Hold Space during boot to open the menu
  # (e.g. to pick a previous generation if a switch fails to boot).
  boot.loader.timeout = 0;

  # Early KMS: load i915 in initrd so modesetting happens at boot. i915 drives
  # the internal panel (eDP-1) for a clean high-res fbcon.
  # NOTE: NVIDIA is intentionally NOT in the initrd. The panel is on Intel,
  # there's no LUKS/decrypt prompt, and loading nvidia in the initrd caused
  # two problems: (1) it bound the dGPU before the main udev was listening,
  # so nixpkgs's bind→power/control=auto fine-grained-PM rule never fired and
  # the GPU could never runtime-suspend; (2) it gave Plymouth a second
  # display-less KMS device (nvidia-drm "Cannot find any crtc") that glitched
  # the splash. nvidia is loaded in the main system via boot.kernelModules.
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  # video= locks the panel to its native 1920x1080@144 mode early.
  # quiet + rd.* params: "silent boot" — keep console noise out so Plymouth's
  # splash is the only thing on screen (press Esc to see logs).
  boot.kernelParams = [
    "nvidia-drm.fbdev=1"
    "nvidia-drm.modeset=1"
    "video=eDP-1:1920x1080@144"
    "quiet"
    "rd.udev.log_level=3"
    "rd.systemd.show_status=auto"
  ];

  # Plymouth boot splash (bgrt theme — OEM/manufacturer logo from the firmware
  # ACPI BGRT table, rendered above a spinner). Reliable on NVIDIA proprietary.
  # `boot.plymouth.enable` auto-adds "splash" to kernelParams; bgrt is built-in
  # so no themePackages needed. Falls back to a plain spinner if the firmware
  # exposes no BGRT. Takes effect on next reboot (initrd rebuild).
  boot.plymouth = {
    enable = true;
    theme = "bgrt";
  };
  boot.consoleLogLevel = 3;
  boot.initrd.verbose = false;

  # Cross-build foreign-arch closures transparently from this x86_64 box.
  # Registers qemu-user via binfmt_misc so the kernel routes aarch64 ELF
  # execution through emulation during `nix build`. Used to iterate on the
  # M2 NixOS-in-UTM (aarch64-linux) config without leaving the laptop.
  # Takes effect after `nh os switch .` + reboot (or `systemctl restart
  # systemd-binfmt`). The M2 VM itself builds natively once booted, so this
  # is only needed for cross-building from the laptop.
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  # --- GPU: NVIDIA RTX 3050 Mobile + Intel iGPU hybrid ---
  # Sway runs on the Intel iGPU only (WLR_DRM_DEVICES below); NVIDIA is kept
  # free of holders so RTD3 can power it off when idle, and opt-in apps reach
  # it via `nvidia-offload` (PRIME). This is the OPPOSITE of the `desk` VM,
  # where NVIDIA is the sole/primary GPU.

  # Restrict wlroots to the Intel iGPU so Sway never opens the NVIDIA device →
  # keeps NVIDIA free of holders → RTD3 can power the GPU off when idle.
  programs.sway.extraOptions = [ "--unsupported-gpu" ]; # required for NVIDIA proprietary
  programs.sway.extraSessionCommands = ''
    export WLR_DRM_DEVICES=/dev/dri/intel
  '';

  # Hide the NVIDIA Vulkan/EGL ICDs from the whole session so no app enumerates
  # (and opens) /dev/dri/renderD129 during loader init. Any open render-node FD
  # pins NVIDIA's runtime-PM count > 0 and blocks RTD3, so the dGPU would never
  # sleep (light stays on). With these set, libvulkan/GLVND load Mesa only →
  # only the Intel node is ever opened → RTD3 can engage. PRIME offload still
  # works via the custom `nvidia-offload` wrapper in environment.systemPackages,
  # which overrides these vars back to the NVIDIA ICDs.
  environment.sessionVariables = {
    VK_ICD_FILENAMES = "${pkgs.mesa}/share/vulkan/icd.d/intel_icd.x86_64.json";
    __EGL_VENDOR_LIBRARY_FILENAMES = "${pkgs.mesa}/share/glvnd/egl_vendor.d/50_mesa.json";
  };

  hardware.graphics.enable = true;

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true; # required for Wayland
    powerManagement.enable = true; # suspends GPU on sleep
    powerManagement.finegrained = true; # RTD3: powers GPU off when idle
    open = false; # proprietary kernel module
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    prime = {
      offload = {
        enable = true;
        # We ship our own `nvidia-offload` (see environment.systemPackages)
        # that also flips VK_ICD_FILENAMES / EGL vendor to NVIDIA, so offloaded
        # apps punch through the Intel-only loader restriction set above.
        enableOffloadCmd = false;
      };
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  # Colon-free stable symlink for the Intel iGPU. WLR_DRM_DEVICES uses ':' as a
  # list separator, so the by-path name (pci-0000:00:02.0-card) breaks parsing.
  # Keyed on PCI path → survives card0/card1 enumeration swaps across reboots.
  #
  # Also force the NVIDIA dGPU into PCI runtime PM (power/control=auto).
  # nixpkgs's built-in fine-grained rule only matches ACTION=="bind"; that's
  # fragile (and was missed entirely when nvidia used to bind in the initrd).
  # Matching "add|bind" covers coldplug replay too, so control=auto is set
  # reliably → with zero clients the GPU enters RTD3 and powers off.
  services.udev.extraRules = ''
    SUBSYSTEM=="drm", ENV{ID_PATH}=="pci-0000:00:02.0", SYMLINK+="dri/intel"
    ACTION=="add|bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
  '';

  # --- Laptop hardware services ---
  services.power-profiles-daemon.enable = true; # balanced/power-saver/performance
  services.upower.enable = true; # battery status via D-Bus
  services.fwupd.enable = true; # LVFS firmware updates (fwupdmgr)

  hardware.bluetooth.enable = true; # BlueZ stack
  hardware.bluetooth.powerOnBoot = true;

  # Bluetooth A2DP codec priority (laptop-only — the VMs have no BT). WirePlumber
  # picks the first codec in the list the device supports, so high-fidelity
  # codecs (LDAC, aptX HD, aptX, AAC) are tried before SBC-XQ / SBC. SBC-XQ uses
  # high-bitpool "Dual Channel" mode for near-CD quality on devices that lack
  # aptX/AAC/LDAC.
  #
  # Role names MUST use underscores (a2dp_source, not a2dp-source) — the SPA
  # bluez5 plugin does exact spa_streq() matching. For a laptop that sends audio
  # to headphones we are the *source* (a2dp_source) and the *audio gateway* for
  # HSP/HFP (hsp_ag / hfp_ag), not the headset/handsfree side.
  services.pipewire.wireplumber.configPackages = [
    (pkgs.writeTextDir "share/wireplumber/wireplumber.conf.d/51-bluetooth-codecs.conf" ''
      monitor.bluez.properties = {
        bluez5.roles = [ "a2dp_source" "a2dp_sink" "hsp_ag" "hfp_ag" ]
        bluez5.codecs = [ "ldac" "aptx_hd" "aptx" "aac" "sbc_xq" "sbc" ]
        bluez5.enable-sbc-xq = true
      }
    '')
  ];

  # --- Printer groups (base user/groups come from _common) ---
  users.users.bob.extraGroups = [ "lp" "lpadmin" "scanner" ];

  # --- System packages (laptop-specific tools + NVIDIA-offload wrapper) ---
  environment.systemPackages = with pkgs; [
    git
    gh
    nh
    aria2
    curl
    wget
    podman
    gnutar
    unzip
    wl-clipboard
    gsettings-desktop-schemas # org.gnome.desktop.interface schema → Vivaldi/Chromium reads color-scheme
    # Printing (network HP printer) — CLI tools
    hplipWithPlugin # hp-setup / hp-info / hp-toolbox / hp-scan (includes the HP binary plugin)
    cups # lp / lpstat / lpadmin / lpinfo user-facing CLI
    nmap # network discovery (locate printer IP + general use)
  ] ++ [
    # Re-enables the NVIDIA Vulkan/EGL ICDs (overriding the session's Intel-only
    # restriction above) for opt-in apps. Usage: nvidia-offload <cmd>.
    (pkgs.writeShellScriptBin "nvidia-offload" ''
      export __NV_PRIME_RENDER_OFFLOAD=1
      export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
      export __GLX_VENDOR_LIBRARY_NAME=nvidia
      export __VK_LAYER_NV_optimus=NVIDIA_only
      export VK_ICD_FILENAMES="${config.hardware.nvidia.package}/share/vulkan/icd.d/nvidia_icd.json"
      export __EGL_VENDOR_LIBRARY_FILENAMES="${config.hardware.nvidia.package}/share/glvnd/egl_vendor.d/10_nvidia.json"
      exec "$@"
    '')
  ];

  # --- Network HP printer (Wi-Fi) ---
  # CUPS is the print daemon; hplipWithPlugin provides the HP backend +
  # proprietary plugin most consumer HP printers (DeskJet/Envy/OfficeJet)
  # require to actually print.
  services.printing = {
    enable = true;
    drivers = [ pkgs.hplipWithPlugin ];
  };
  # Avahi: mDNS discovery so the printer is reachable as <hostname>.local and
  # shows up in `lpinfo -v`. Required for driverless IPP discovery.
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };
  # Scanning via SANE (HP all-in-one). Uses hplipWithPlugin's backend.
  hardware.sane.enable = true;
  hardware.sane.extraBackends = [ pkgs.hplipWithPlugin ];

  # This value determines the NixOS release from which the default settings for
  # stateful data were taken. Leave it at the version of the first install.
  system.stateVersion = "26.05";
}
