# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Hardware scan — generated by `nixos-generate-config`. Replace this file
      # when porting to a new machine (do NOT reuse another machine's disk UUIDs).
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  # ESP is 1 GB. Each entry ≈ 66 MB (13 MB kernel + 53 MB initrd; NVIDIA is
  # intentionally NOT in the initrd, so it's small). 5 entries ≈ 340 MB,
  # leaving ~680 MB headroom. Stay ≤ ~10.
  boot.loader.systemd-boot.configurationLimit = 5;
  boot.loader.efi.canTouchEfiVariables = true;
  # Boot immediately — no menu shown. Hold Space during boot to open the menu
  # (e.g. to pick a previous generation if a switch fails to boot).
  boot.loader.timeout = 0;

  # Early KMS: load i915 in initrd so modesetting happens at boot.
  # i915 drives the internal panel (eDP-1) for a clean high-res fbcon.
  # NOTE: NVIDIA is intentionally NOT in the initrd. The panel is on Intel,
  # there's no LUKS/decrypt prompt, and loading nvidia in the initrd caused
  # two problems: (1) it bound the dGPU before the main udev was listening,
  # so nixpkgs's bind→power/control=auto fine-grained-PM rule never fired and
  # the GPU could never runtime-suspend; (2) it gave Plymouth a second
  # display-less KMS device (nvidia-drm "Cannot find any crtc") that glitched
  # the splash. nvidia is loaded in the main system via boot.kernelModules.
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  # video= locks the panel to its native 1920x1080@144 mode early.
  # quiet + rd.* params: "silent boot" — keep console noise out so
  # Plymouth's splash is the only thing on screen (press Esc to see logs).
  boot.kernelParams = [
    "nvidia-drm.fbdev=1"
    "nvidia-drm.modeset=1"
    "video=eDP-1:1920x1080@144"
    "quiet"
    "rd.udev.log_level=3"
    "rd.systemd.show_status=auto"
  ];

  # Plymouth boot splash (bgrt theme — OEM/manufacturer logo from the
  # firmware ACPI BGRT table, rendered above a spinner). Reliable on NVIDIA
  # proprietary. `boot.plymouth.enable` auto-adds "splash" to kernelParams;
  # bgrt is built-in so no themePackages needed. Falls back to a plain spinner
  # if the firmware exposes no BGRT. Takes effect on next reboot (initrd rebuild).
  boot.plymouth = {
    enable = true;
    theme = "bgrt";
  };
  boot.consoleLogLevel = 3;
  boot.initrd.verbose = false;

  # Cross-build foreign-arch closures transparently from this x86_64 box.
  # Registers qemu-user via binfmt_misc so the kernel routes aarch64 ELF
  # execution through emulation during `nix build`. Used to iterate on the
  # M2 NixOS-in-UTM (aarch64-linux) config without leaving the desktop.
  # Takes effect after `nh os switch .` + reboot (or `systemctl restart
  # systemd-binfmt`). The M2 VM itself builds natively once booted, so this
  # is only needed for cross-building from the desktop.
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Asia/Tokyo";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_DK.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "da_DK.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };

  # Configure keymap (XKB): US(altgr-intl) is the default (group 0), Graphite
  # (custom) is group 1 — both carry the altgr-intl AltGr layer for Danish
  # (ae/oslash/aring) and dead keys. Toggle groups in the Sway config below via
  # xkb_switch_layout (grp:win_space_toggle would collide with Noctalia's $mod+space).
  services.xserver.xkb = {
    layout = "us,graphite";
    variant = "altgr-intl,";
    extraLayouts.graphite = {
      description = "Graphite (intl., with AltGr dead keys)";
      languages = [ "eng" ];
      symbolsFile = ../../xkb/graphite;
    };
  };

  # Configure console keymap
  console.keyMap = "us";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.bob = {
    isNormalUser = true;
    description = "Bob";
    extraGroups = [ "networkmanager" "wheel" "lp" "lpadmin" "scanner" ];
    packages = with pkgs; [];
    shell = pkgs.zsh;
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Zsh: register in /etc/shells so it can be a login shell.
  # Prompt, plugins, and keybinds are managed by home-manager (home/default.nix).
  programs.zsh.enable = true;

  # Enable Sway
  programs.sway.enable = true;
  programs.sway.extraOptions = [ "--unsupported-gpu" ]; # Required for NVIDIA proprietary driver
  programs.sway.wrapperFeatures.gtk = true; # GTK env vars for app theming
  # Restrict wlroots to the Intel iGPU so Sway never opens the NVIDIA device.
  # Keeps NVIDIA free of holders → RTD3 can power the GPU off when idle.
  # Offload apps still reach the GPU via `nvidia-offload` (PRIME).
  programs.sway.extraSessionCommands = ''
    export WLR_DRM_DEVICES=/dev/dri/intel
  '';

  # Sway config + Noctalia keybinds are managed by home-manager (home/sway.nix),
  # written to ~/.config/sway/ — portable across NixOS and Ubuntu.

  # Make Electron apps use Wayland
  environment.variables.NIXOS_OZONE_WL = "1";

  # Hide the NVIDIA Vulkan/EGL ICDs from the whole session so no app
  # enumerates (and opens) /dev/dri/renderD129 during loader init. Any open
  # render-node FD pins NVIDIA's runtime-PM count > 0 and blocks RTD3, so the
  # dGPU would never sleep (light stays on). With these set, libvulkan/GLVND
  # load Mesa only → only the Intel node is ever opened → RTD3 can engage.
  # PRIME offload still works via the custom `nvidia-offload` wrapper below,
  # which overrides these vars back to the NVIDIA ICDs.
  environment.sessionVariables = {
    VK_ICD_FILENAMES = "${pkgs.mesa}/share/vulkan/icd.d/intel_icd.x86_64.json";
    __EGL_VENDOR_LIBRARY_FILENAMES = "${pkgs.mesa}/share/glvnd/egl_vendor.d/50_mesa.json";
  };

  # Battery Efficiency
  services.power-profiles-daemon.enable = true; # Power profiles (balanced/power-saver/performance)
  services.upower.enable = true; # Battery status reporting via D-Bus

  # Compressed RAM swap (zstd). Normally stays empty; under memory pressure the
  # kernel compresses cold pages into RAM instead of hitting the 8.8G disk-swap
  # partition (which stays as a lower-priority fallback). zram is swapon'd with a
  # higher priority, so it's used first and the disk swap only catches overflow.
  # Net effect: stays responsive when RAM fills up instead of grinding on disk.
  zramSwap = {
    enable = true;
    algorithm = "zstd";
  };

  # Firmware updates (LVFS). `fwupdmgr refresh && fwupdmgr get-updates` checks
  # for BIOS/EC updates — an MSI firmware update is the one thing that might
  # officially enable battery charge limiting, so worth having regardless.
  services.fwupd.enable = true;

  # Audio
  security.rtkit.enable = true; # Realtime scheduling for PipeWire (low-latency audio)
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true; # 32-bit ALSA app compatibility (e.g. some games/Wine)
    pulse.enable = true; # Emulates PulseAudio so modern apps work seamlessly
    # Bluetooth A2DP codec priority: WirePlumber picks the first codec in the
    # list that the device supports, so high-fidelity codecs (LDAC, aptX HD,
    # aptX, AAC) are tried before falling back to SBC-XQ / SBC. SBC-XQ uses
    # high-bitpool "Dual Channel" mode for near-CD quality on devices that
    # lack aptX/AAC/LDAC — works with virtually every BT headphone.
    #
    # Role names MUST use underscores (a2dp_source, not a2dp-source) — the SPA
    # bluez5 plugin does exact spa_streq() matching. For a desktop that sends
    # audio to headphones we are the *source* (a2dp_source) and the *audio
    # gateway* for HSP/HFP (hsp_ag / hfp_ag), not the headset/handsfree side.
    wireplumber.configPackages = [
      (pkgs.writeTextDir "share/wireplumber/wireplumber.conf.d/51-bluetooth-codecs.conf" ''
        monitor.bluez.properties = {
          bluez5.roles = [ "a2dp_source" "a2dp_sink" "hsp_ag" "hfp_ag" ]
          bluez5.codecs = [ "ldac" "aptx_hd" "aptx" "aac" "sbc_xq" "sbc" ]
          bluez5.enable-sbc-xq = true
        }
      '')
    ];
  };

  # Bluetooth
  hardware.bluetooth.enable = true; # BlueZ stack (daemon + kernel modules)
  hardware.bluetooth.powerOnBoot = true; # Power on adapter automatically at boot

  # Colon-free stable symlink for the Intel iGPU. WLR_DRM_DEVICES uses ':' as a
  # list separator, so the by-path name (pci-0000:00:02.0-card) breaks parsing.
  # Keyed on PCI path → survives card0/card1 enumeration swaps across reboots.
  #
  # Also force the NVIDIA dGPU into PCI runtime PM (power/control=auto).
  # nixpkgs's built-in fine-grained rule only matches ACTION=="bind"; that's
  # fragile (and was missed entirely when nvidia used to bind in the initrd).
  # Matching "add|bind" covers coldplug replay too, so control=auto is set
  # reliably → with zero clients the GPU enters RTD3 and powers off.
  services.udev.extraRules = ''
    SUBSYSTEM=="drm", ENV{ID_PATH}=="pci-0000:00:02.0", SYMLINK+="dri/intel"
    ACTION=="add|bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
  '';

  # Modern graphics stack
  hardware.graphics.enable = true;

  # NVIDIA (RTX 3050 Mobile, hybrid with Intel iGPU)
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true; # Required for Wayland
    powerManagement.enable = true; # Suspends GPU on sleep
    powerManagement.finegrained = true; # RTD3: powers GPU off when idle
    open = false; # Proprietary kernel module
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    prime = {
      offload = {
        enable = true;
        # We ship our own `nvidia-offload` (see environment.systemPackages)
        # that also flips VK_ICD_FILENAMES / EGL vendor to NVIDIA, so offloaded
        # apps punch through the Intel-only loader restriction set above.
        enableOffloadCmd = false;
      };
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  # Essential System Tools
  environment.systemPackages = with pkgs; [
    git
    gh
    nh
    aria2
    curl
    wget
    gitbutler
    podman
    gnutar
    unzip
    wl-clipboard
    gsettings-desktop-schemas  # org.gnome.desktop.interface schema → Vivaldi/Chromium reads color-scheme
    # Printing (network HP printer) — CLI tools
    hplipWithPlugin   # hp-setup / hp-info / hp-toolbox / hp-scan (includes the HP binary plugin)
    cups              # lp / lpstat / lpadmin / lpinfo user-facing CLI
    nmap              # network discovery (locate printer IP + general use)
  ] ++ [
    # Re-enables the NVIDIA Vulkan/EGL ICDs (overriding the session's
    # Intel-only restriction) for opt-in apps. Usage: nvidia-offload <cmd>.
    # Ubuntu gets a simpler version via home-manager (no VK_ICD override needed).
    (pkgs.writeShellScriptBin "nvidia-offload" ''
      export __NV_PRIME_RENDER_OFFLOAD=1
      export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
      export __GLX_VENDOR_LIBRARY_NAME=nvidia
      export __VK_LAYER_NV_optimus=NVIDIA_only
      export VK_ICD_FILENAMES="${config.hardware.nvidia.package}/share/vulkan/icd.d/nvidia_icd.json"
      export __EGL_VENDOR_LIBRARY_FILENAMES="${config.hardware.nvidia.package}/share/glvnd/egl_vendor.d/10_nvidia.json"
      exec "$@"
    '')
  ];

  fonts.packages = with pkgs; [
    nerd-fonts.commit-mono
    nerd-fonts.departure-mono
    lexend
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
    atkinson-hyperlegible-mono
    atkinson-hyperlegible-next
    hubot-sans
    mona-sans
    alegreya
    alegreya-sans
    fraunces
    recursive
  ];

  # The Python Secret Sauce: nix-ld
  # This allows pre-compiled binaries (like those uv/pip download) to run
  programs.nix-ld.enable = true;

  # direnv is managed by home-manager (home/default.nix) so it works on both
  # NixOS and Ubuntu. nix-direnv caches `nix develop` results for instant entry.

  # dconf (D-Bus settings store). The Noctalia `color-scheme-sync` hook writes
  # the freedesktop color-scheme here so Chromium-based apps (Vivaldi) follow
  # the active light/dark mode.
  programs.dconf.enable = true;

  # Bridge the dconf color-scheme to the freedesktop portal interface that
  # Chromium-based apps (Vivaldi) query for prefers-color-scheme. Without this
  # the gtk backend never runs, so Vivaldi can't see the value dconf holds.
  xdg.portal = {
    enable = true;
    xdgOpenUsePortal = false;              # keep Vivaldi's own link handling
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    config.common.default = [ "gtk" ];
  };

  # Nix Settings
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;  # hardlink-dedup on every build
  };

  # Weekly GC: drop generations older than 14 days, then collect garbage.
  # At ~2 rebuilds/day keeps ~28 generations — well above the 5 boot-menu
  # entries. Cleans system + home-manager profiles; persistent (default) lets
  # missed runs (laptop suspended) catch up.
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # Periodic full optimise pass (complements auto-optimise-store).
  nix.optimise.automatic = true;

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # --- Printing (network HP printer over Wi-Fi) ---
  # CUPS is the print daemon; hplipWithPlugin provides the HP backend +
  # proprietary plugin most consumer HP printers (DeskJet/Envy/OfficeJet)
  # require to actually print.
  services.printing = {
    enable = true;
    drivers = [ pkgs.hplipWithPlugin ];
  };

  # Avahi: mDNS discovery so the printer is reachable as <hostname>.local
  # and shows up in `lpinfo -v`. Required for driverless IPP discovery.
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };

  # Scanning via SANE (HP all-in-one). Uses hplipWithPlugin's backend.
  hardware.sane.enable = true;
  hardware.sane.extraBackends = [ pkgs.hplipWithPlugin ];

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "26.05"; # Did you read the comment?

}
